import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { Candidacy } from '../../candidacy/entities/candidacy.entity';
import { ReminderStatus, ReminderType, ReminderPriority } from '../enums';

@Entity({ name: 'reminder' })
@Index(['dueDate', 'status'])
@Index(['status', 'priority'])
export class Reminder {
  @PrimaryGeneratedColumn('increment', { name: 'id_reminder' })
  id: number;

  @Column({ name: 'id_candidacy' })
  candidacyId: number;

  @ManyToOne(() => Candidacy, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'id_candidacy' })
  candidacy: Candidacy;

  @Column({ name: 'due_date', type: 'timestamptz' })
  dueDate: Date;

  @Column({
    name: 'reminder_type',
    type: 'varchar',
    length: 50,
    default: ReminderType.CUSTOM,
  })
  reminderType: ReminderType;

  @Column({
    type: 'varchar',
    length: 50,
    default: ReminderStatus.PENDING,
  })
  status: ReminderStatus;

  @Column({
    type: 'varchar',
    length: 50,
    default: ReminderPriority.MEDIUM,
  })
  priority: ReminderPriority;

  @Column({ type: 'text', nullable: true })
  comment?: string;

  @Column({ name: 'auto_generated', default: true })
  autoGenerated: boolean;

  @Column({ name: 'snoozed_until', type: 'timestamptz', nullable: true })
  snoozedUntil?: Date;

  @Column({ name: 'completed_at', type: 'timestamptz', nullable: true })
  completedAt?: Date;

  @Column({ name: 'original_due_date', type: 'timestamptz', nullable: true })
  originalDueDate?: Date;

  @CreateDateColumn({
    name: 'created_at',
    type: 'timestamptz',
    default: () => 'NOW()',
  })
  createdAt: Date;
}
