import {
  IsNumber,
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  IsDateString,
  IsEnum,
} from 'class-validator';
import { ReminderStatus, ReminderType, ReminderPriority } from '../enums';

export class CreateReminderDto {
  @IsNumber()
  candidacyId: number;

  @IsDateString()
  dueDate: string;

  @IsEnum(ReminderType)
  reminderType: ReminderType;

  @IsEnum(ReminderStatus)
  @IsOptional()
  status?: ReminderStatus = ReminderStatus.PENDING;

  @IsEnum(ReminderPriority)
  @IsOptional()
  priority?: ReminderPriority = ReminderPriority.MEDIUM;

  @IsOptional()
  @IsString()
  comment?: string;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean = true;

  @IsOptional()
  @IsDateString()
  snoozedUntil?: string;

  @IsOptional()
  @IsDateString()
  completedAt?: string;

  @IsOptional()
  @IsDateString()
  originalDueDate?: string;
}
