import { ReminderStatus, ReminderType, ReminderPriority } from '../enums';

export class ReminderResponseDto {
  id: number;
  candidacyId: number;
  dueDate: Date;
  reminderType: ReminderType;
  status: ReminderStatus;
  priority: ReminderPriority;
  comment?: string;
  autoGenerated: boolean;
  snoozedUntil?: Date;
  completedAt?: Date;
  originalDueDate?: Date;
  createdAt: Date;

  // Champs calculés (ajoutés par le service)
  daysOverdue?: number;
  isOverdue?: boolean;
  candidacy?: any; // Sera typé plus tard avec la relation
}
