// ============================================================================
// ENUMS
// ============================================================================

export enum ReminderStatus {
  PENDING = 'PENDING',       // En attente
  SNOOZED = 'SNOOZED',      // Reporté
  COMPLETED = 'COMPLETED',   // Complété
  CANCELLED = 'CANCELLED',   // Annulé
  EXPIRED = 'EXPIRED'        // Expiré (jamais complété)
}

export enum ReminderType {
  FIRST_FOLLOW_UP = 'FIRST_FOLLOW_UP',      // J+5
  SECOND_FOLLOW_UP = 'SECOND_FOLLOW_UP',    // J+10
  FINAL_FOLLOW_UP = 'FINAL_FOLLOW_UP',      // J+15
  CUSTOM = 'CUSTOM',                         // Créé manuellement
  INTERVIEW = 'INTERVIEW',                   // Entretien programmé
  DEADLINE = 'DEADLINE'                      // Date limite
}

export enum ReminderPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

// ============================================================================
// MAIN REMINDER INTERFACE
// ============================================================================

export interface Reminder {
  id: number;
  candidacyId: number;
  dueDate: string;
  reminderType: ReminderType;
  status: ReminderStatus;
  priority?: ReminderPriority;
  comment?: string;
  autoGenerated: boolean;
  snoozedUntil?: string;
  completedAt?: string;
  originalDueDate?: string;
  createdAt: string;

  // Relations (optionnelles, viennent du backend avec includes)
  candidacy?: {
    id: number;
    currentStatus: string;
    applicationDate: string;
    company: {
      name: string;
      logoUrl?: string;
    };
    jobOffer: {
      title: string;
      location?: string;
    };
  };
}

// ============================================================================
// REMINDER DASHBOARD DATA
// ============================================================================

export interface ReminderDashboard {
  summary: {
    total: number;
    overdue: number;
    today: number;
    thisWeek: number;
    upcoming: number;
  };
  byPriority: {
    CRITICAL: number;
    HIGH: number;
    MEDIUM: number;
    LOW: number;
  };
  byCandidacyStatus: { [key: string]: number };
  criticalReminders: Reminder[];

  // Listes filtrées pour affichage interactif
  overdueReminders: Reminder[];
  todayReminders: Reminder[];
  thisWeekReminders: Reminder[];
  upcomingReminders: Reminder[];
}

// ============================================================================
// DTOs (Data Transfer Objects)
// ============================================================================

export interface CreateReminderDto {
  candidacyId: number;
  dueDate: string;
  reminderType: ReminderType;
  status?: ReminderStatus;
  comment?: string;
  autoGenerated?: boolean;
}

export interface UpdateReminderDto {
  dueDate?: string;
  reminderType?: ReminderType;
  status?: ReminderStatus;
  priority?: ReminderPriority;
  comment?: string;
}

export interface SnoozeReminderDto {
  snoozeDays: number;
}

export interface CompleteReminderDto {
  comment?: string;
}

// ============================================================================
// HELPER INTERFACES
// ============================================================================

export interface ReminderWithDaysInfo extends Reminder {
  daysOverdue?: number;
  daysUntilDue?: number;
  isOverdue: boolean;
  isToday: boolean;
  isThisWeek: boolean;
}

// ============================================================================
// REMINDER FILTERS
// ============================================================================

export interface ReminderFilters {
  status?: ReminderStatus[];
  priority?: ReminderPriority[];
  reminderType?: ReminderType[];
  candidacyStatus?: string[];
  dateFrom?: string;
  dateTo?: string;
  isOverdue?: boolean;
}
