export interface Reminder {
  id?: number;
  candidacyId: number;
  dueDate: Date;
  reminderType: ReminderType;
  status: ReminderStatus;
  comment?: string;
  autoGenerated: boolean;
  createdAt?: Date;
  candidacy?: any;
}

export enum ReminderType {
  FIRST_FOLLOW_UP = 'FIRST_FOLLOW_UP',
  SECOND_FOLLOW_UP = 'SECOND_FOLLOW_UP',
  FINAL_FOLLOW_UP = 'FINAL_FOLLOW_UP',
  INTERVIEW_PREPARATION = 'INTERVIEW_PREPARATION',
  CUSTOM = 'CUSTOM'
}

export enum ReminderStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  DISMISSED = 'DISMISSED',
  OVERDUE = 'OVERDUE'
}

export interface CreateReminderRequest {
  candidacyId: number;
  dueDate: string;
  reminderType: ReminderType;
  status: ReminderStatus;
  comment?: string;
  autoGenerated: boolean;
}
